/**
 * @file MediaCard - Optimized with Thumbnails & Lazy Loading
 * @description Display media card with automatic thumbnail loading (Phase 3)
 * @pattern Uses Intersection Observer API for lazy loading
 * @phase4 Enhanced with smooth animations and full accessibility support
 */
"use client";

import { useState, useEffect, useRef } from "react";
import { format } from "date-fns";
import { fr } from "date-fns/locale";
import { Folder, Eye } from "lucide-react";
import { cn } from "@/lib/utils";
import type { MediaItemExtendedDTO } from "@/lib/schemas/media";

interface MediaCardProps {
  media: MediaItemExtendedDTO;
  isSelected?: boolean;
  selectionMode?: boolean;
  onSelect?: (media: MediaItemExtendedDTO) => void;
  onKeyboardSelect?: (media: MediaItemExtendedDTO, event: React.KeyboardEvent) => void;
}

export function MediaCard({
  media,
  isSelected,
  selectionMode,
  onSelect,
  onKeyboardSelect,
}: MediaCardProps) {
  const [isVisible, setIsVisible] = useState(false);
  const [imageLoaded, setImageLoaded] = useState(false);
  const [imageError, setImageError] = useState(false);
  const cardRef = useRef<HTMLDivElement>(null);

  const isImage = media.mime?.startsWith("image/") ?? false;

  // Thumbnail path (generated by Phase 3 API)
  const thumbnailPath = media.thumbnail_path;

  // Original image URL (fallback if thumbnail doesn't exist)
  const originalUrl = `${process.env.NEXT_PUBLIC_SUPABASE_URL}/storage/v1/object/public/medias/${media.storage_path}`;

  // Prefer thumbnail if available, otherwise use original
  const imageUrl = thumbnailPath
    ? `${process.env.NEXT_PUBLIC_SUPABASE_URL}/storage/v1/object/public/medias/${thumbnailPath}`
    : originalUrl;

  // Lazy loading with Intersection Observer
  useEffect(() => {
    if (!cardRef.current) return;

    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting) {
            setIsVisible(true);
            observer.disconnect();
          }
        });
      },
      {
        rootMargin: "50px", // Start loading 50px before entering viewport
      }
    );

    observer.observe(cardRef.current);

    return () => {
      observer.disconnect();
    };
  }, []);

  // Keyboard navigation handler (Phase 4.2 - Accessibility)
  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === " " || e.key === "Enter") {
      e.preventDefault();
      onSelect?.(media);
      onKeyboardSelect?.(media, e);
    }
  };

  const formattedDate = media.created_at
    ? format(new Date(media.created_at), "dd MMM yyyy", { locale: fr })
    : "N/A";

  return (
    <div
      ref={cardRef}
      className={cn(
        "group relative overflow-hidden rounded-lg border bg-card cursor-pointer",
        // Phase 4.1 - Smooth animations
        "transition-all duration-200 ease-in-out",
        "hover:shadow-lg hover:-translate-y-1",
        // Accessibility focus styles
        "focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2",
        selectionMode && "hover:border-primary",
        isSelected && "ring-2 ring-primary border-primary"
      )}
      onClick={() => onSelect?.(media)}
      onKeyDown={handleKeyDown}
      role="button"
      tabIndex={0}
      aria-label={`${isSelected ? "Désélectionner" : "Sélectionner"} ${media.filename}`}
      aria-selected={isSelected}
    >
      {/* Selection Checkbox */}
      {selectionMode && (
        <div className="absolute top-2 right-2 z-10">
          <div
            className={cn(
              "h-6 w-6 rounded-full border-2 flex items-center justify-center",
              // Phase 4.1 - Smooth checkbox transition
              "transition-all duration-150 ease-in-out",
              isSelected && "scale-110",
              isSelected
                ? "bg-primary border-primary"
                : "bg-background/80 border-muted-foreground/50"
            )}
            role="checkbox"
            aria-checked={isSelected}
          >
            {isSelected && (
              <svg
                className="h-4 w-4 text-primary-foreground animate-in fade-in duration-150"
                fill="currentColor"
                viewBox="0 0 20 20"
                aria-hidden="true"
              >
                <path
                  fillRule="evenodd"
                  d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"
                  clipRule="evenodd"
                />
              </svg>
            )}
          </div>
        </div>
      )}

      {/* Badge for thumbnail status */}
      {thumbnailPath && (
        <div className="absolute top-2 left-2 z-10">
          <span className="inline-flex items-center gap-1 rounded-full bg-green-500/80 px-2 py-0.5 text-xs text-white backdrop-blur-sm">
            <svg
              className="h-3 w-3"
              fill="none"
              stroke="currentColor"
              viewBox="0 0 24 24"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M5 13l4 4L19 7"
              />
            </svg>
            Optimized
          </span>
        </div>
      )}

      {/* Image Container */}
      <div className="aspect-square overflow-hidden bg-muted relative">
        {isImage ? (
          <>
            {/* Loading skeleton */}
            {!imageLoaded && !imageError && isVisible && (
              <div 
                className="absolute inset-0 animate-pulse bg-muted"
                role="status"
                aria-label="Chargement de l'image"
              />
            )}

            {/* Lazy loaded image */}
            {isVisible && !imageError && (
              <img
                src={imageUrl}
                alt={media.alt_text ?? media.filename ?? undefined}
                className={cn(
                  "h-full w-full object-cover transition-all duration-300",
                  imageLoaded
                    ? "opacity-100 group-hover:scale-105"
                    : "opacity-0"
                )}
                loading="lazy"
                onLoad={() => setImageLoaded(true)}
                onError={() => {
                  setImageError(true);
                  // If thumbnail fails, try original image
                  if (thumbnailPath) {
                    console.warn(
                      `[MediaCard] Thumbnail failed for ${media.filename}, falling back to original`
                    );
                  }
                }}
              />
            )}

            {/* Error fallback */}
            {imageError && (
              <div 
                className="flex h-full w-full items-center justify-center text-muted-foreground"
                role="img"
                aria-label="Erreur de chargement d'image"
              >
                <svg
                  className="h-12 w-12"
                  fill="none"
                  stroke="currentColor"
                  viewBox="0 0 24 24"
                  aria-hidden="true"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth="2"
                    d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z"
                  />
                </svg>
              </div>
            )}
          </>
        ) : (
          <div 
            className="flex h-full items-center justify-center"
            role="img"
            aria-label={`Fichier ${media.mime?.split("/")[0] ?? "inconnu"}`}
          >
            <p className="text-sm text-muted-foreground">
              {media.mime?.split("/")[0] ?? "fichier"}
            </p>
          </div>
        )}
      </div>

      {/* Metadata */}
      <div className="p-3">
        <p className="truncate text-sm font-medium">{media.filename}</p>
        <p className="text-xs text-muted-foreground">
          {media.size_bytes !== null
            ? formatFileSize(media.size_bytes)
            : "Taille inconnue"}
        </p>

        {/* Tags */}
        {media.tags.length > 0 && (
          <div 
            className="mt-2 flex flex-wrap gap-1"
            role="list"
            aria-label="Tags du média"
          >
            {media.tags.slice(0, 3).map((tag) => (
              <span
                key={tag.id}
                className="inline-flex items-center gap-1 rounded-full bg-secondary px-2 py-0.5 text-xs"
                role="listitem"
              >
                <div
                  className="h-2 w-2 rounded-full"
                  style={{ backgroundColor: tag.color ?? undefined }}
                  aria-hidden="true"
                />
                {tag.name}
              </span>
            ))}
            {media.tags.length > 3 && (
              <span 
                className="text-xs text-muted-foreground"
                aria-label={`${media.tags.length - 3} tags supplémentaires`}
              >
                +{media.tags.length - 3}
              </span>
            )}
          </div>
        )}

        {/* Folder & Usage Info */}
        <div className="mt-2 flex flex-col gap-1">
          {/* Folder location */}
          <div className="flex items-center gap-1.5 text-xs text-muted-foreground" title={media.folder?.name ?? "Racine"}>
            <Folder className="h-3 w-3 flex-shrink-0" aria-hidden="true" />
            <span className="truncate">
              {media.folder?.name ?? "Racine"}
            </span>
          </div>

          {/* Public usage indicator - Placeholder for Phase 4.3+ */}
          {/* TODO Phase 4.3: Implémenter le tracking d'usage pour vérifier si le média est utilisé dans app/(marketing) */}
          {/* Exemple d'utilisation future:
          {media.is_used_public && (
            <div className="flex items-center gap-1.5 text-xs text-emerald-600 dark:text-emerald-400">
              <Eye className="h-3 w-3 flex-shrink-0" aria-hidden="true" />
              <span>Utilisé sur le site</span>
            </div>
          )}
          */}
        </div>
      </div>
    </div>
  );
}

function formatFileSize(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}
