-- Migration: allow_admin_update_profiles
-- Purpose: allow administrators to update any profile (update policy change)
-- Affected table: public.profiles
-- Generated by: supabase db diff (feature/backoffice)
-- Note: this migration replaces the previous restrictive update policy
-- Special considerations: keeps policy permissive; uses select auth.uid() for initplan optimization

drop policy if exists "Users can update their own profile" on "public"."profiles";

create policy "Users can update their own profile OR admins can update any profile"
  on "public"."profiles"
  as permissive
  for update
  to authenticated
  using (
    (
      (select auth.uid()) = user_id
      or
      (select public.is_admin()) = true
    )
  )
  with check (
    (
      (select auth.uid()) = user_id
      or
      (select public.is_admin()) = true
    )
  );



