-- Seed initial pour la table public.spectacles
-- NOTE: Ce seed utilise des champs alignés avec le schéma actuel (voir knowledge-base §6.1)

insert into public.spectacles (title, slug, status, description, short_description, genre, duration_minutes, casting, premiere, image_url, public, awards)
values
  (
    'Les Murmures du Temps',
    'les-murmures-du-temps',
    'published',
    'Un voyage poétique à travers les âges, où passé et présent se rencontrent dans un dialogue bouleversant. Cette création originale explore les liens invisibles qui nous unissent à travers le temps.',
    'Voyage poétique entre passé et présent.',
    'Drame contemporain',
    90,
    4,
    '2023-10-15T20:30:00+02:00',
    'https://images.pexels.com/photos/3184418/pexels-photo-3184418.jpeg?auto=compress&cs=tinysrgb&w=1200',
    true,
    ARRAY['Nominé aux Molières 2024']
  ),
  (
    'Fragments d''Éternité',
    'fragments-d-eternite',
    'published',
    'Une création originale qui explore les liens invisibles qui nous unissent, entre rire et larmes. Un spectacle touchant sur la condition humaine et nos quêtes de sens.',
    'Création originale sur les liens invisibles.',
    'Création originale',
    105,
    6,
    '2024-01-12T20:30:00+01:00',
    'https://images.pexels.com/photos/3184339/pexels-photo-3184339.jpeg?auto=compress&cs=tinysrgb&w=1200',
    true,
    null
  ),
  (
    'La Danse des Ombres',
    'la-danse-des-ombres',
    'archived',
    'Adaptation moderne d''un classique, revisité avec audace et sensibilité par notre équipe artistique.',
    'Classique revisité avec audace.',
    'Classique revisité',
    95,
    5,
    '2023-05-10T20:30:00+02:00',
    'https://images.pexels.com/photos/3184340/pexels-photo-3184340.jpeg?auto=compress&cs=tinysrgb&w=1200',
    true,
    ARRAY['Prix du Public - Festival d''Avignon']
  ),
  (
    'Échos de Liberté',
    'echos-de-liberte',
    'archived',
    'Un spectacle engagé sur les droits humains et la liberté d''expression dans le monde contemporain.',
    'Spectacle engagé sur les droits humains.',
    'Théâtre documentaire',
    100,
    4,
    '2022-03-18T20:30:00+01:00',
    'https://images.pexels.com/photos/3184421/pexels-photo-3184421.jpeg?auto=compress&cs=tinysrgb&w=1200',
    true,
    ARRAY['Mention spéciale - Théâtre et Société']
  ),
  (
    'Rêves d''Enfance',
    'reves-d-enfance',
    'archived',
    'Un spectacle familial poétique qui ravive la magie de l''enfance chez petits et grands.',
    'Spectacle familial poétique.',
    'Tout public',
    80,
    3,
    '2021-11-02T19:00:00+01:00',
    'https://images.pexels.com/photos/3184465/pexels-photo-3184465.jpeg?auto=compress&cs=tinysrgb&w=1200',
    true,
    null
  ),
  (
    'Solitudes Partagées',
    'solitudes-partagees',
    'archived',
    'Une réflexion intimiste sur la solitude moderne et les moyens de créer du lien dans notre société.',
    'Réflexion intimiste sur la solitude.',
    'Drame psychologique',
    110,
    2,
    '2020-09-25T20:00:00+02:00',
    'https://images.pexels.com/photos/3184338/pexels-photo-3184338.jpeg?auto=compress&cs=tinysrgb&w=1200',
    true,
    ARRAY['Prix de la Critique']
  ),
  (
    'Mémoires de Guerre',
    'memoires-de-guerre',
    'archived',
    'Un témoignage bouleversant sur les survivants de guerre et la transmission de la mémoire.',
    'Témoignage sur la mémoire de guerre.',
    'Théâtre historique',
    120,
    6,
    '2019-11-11T20:30:00+01:00',
    'https://images.pexels.com/photos/3184396/pexels-photo-3184396.jpeg?auto=compress&cs=tinysrgb&w=1200',
    true,
    ARRAY['Grand Prix du Jury - Festival de Nancy']
  ),
  (
    'Les Voix du Silence',
    'les-voix-du-silence',
    'archived',
    'Spectacle inclusif donnant la parole aux personnes sourdes et malentendantes.',
    'Spectacle inclusif sur la surdité.',
    'Théâtre social',
    85,
    5,
    '2019-06-15T20:00:00+02:00',
    'https://images.pexels.com/photos/3184327/pexels-photo-3184327.jpeg?auto=compress&cs=tinysrgb&w=1200',
    true,
    ARRAY['Prix de l''Innovation Sociale']
  ),
  (
    'Nuit Blanche à Paris',
    'nuit-blanche-a-paris',
    'archived',
    'Une comédie romantique pleine de rebondissements dans les rues de la capitale.',
    'Comédie romantique parisienne.',
    'Comédie',
    95,
    4,
    '2018-12-20T20:30:00+01:00',
    'https://images.pexels.com/photos/3184354/pexels-photo-3184354.jpeg?auto=compress&cs=tinysrgb&w=1200',
    true,
    null
  ),
  (
    'L''Appel de la Forêt',
    'l-appel-de-la-foret',
    'archived',
    'Adaptation théâtrale du chef-d''œuvre de Jack London, entre aventure et introspection.',
    'Adaptation de Jack London.',
    'Aventure dramatique',
    105,
    3,
    '2018-03-22T20:00:00+01:00',
    'https://images.pexels.com/photos/3184372/pexels-photo-3184372.jpeg?auto=compress&cs=tinysrgb&w=1200',
    true,
    ARRAY['Coup de Cœur du Public']
  ),
  (
    'Portraits de Famille',
    'portraits-de-famille',
    'archived',
    'Une chronique familiale touchante sur trois générations de femmes.',
    'Chronique familiale sur trois générations.',
    'Drame familial',
    115,
    7,
    '2017-10-05T20:30:00+02:00',
    'https://images.pexels.com/photos/3184387/pexels-photo-3184387.jpeg?auto=compress&cs=tinysrgb&w=1200',
    true,
    ARRAY['Prix de la Meilleure Interprétation Féminine']
  ),
  (
    'Renaissance',
    'renaissance',
    'archived',
    'Un spectacle musical célébrant la renaissance culturelle après les temps difficiles.',
    'Spectacle musical sur la renaissance.',
    'Comédie musicale',
    130,
    8,
    '2017-04-18T19:30:00+02:00',
    'https://images.pexels.com/photos/3184445/pexels-photo-3184445.jpeg?auto=compress&cs=tinysrgb&w=1200',
    true,
    null
  ),
  (
    'Les Chemins de Traverse',
    'les-chemins-de-traverse',
    'archived',
    'Un road-movie théâtral sur la quête d''identité et les rencontres qui changent une vie.',
    'Road-movie théâtral.',
    'Drame contemporain',
    100,
    4,
    '2016-09-12T20:00:00+02:00',
    'https://images.pexels.com/photos/3184423/pexels-photo-3184423.jpeg?auto=compress&cs=tinysrgb&w=1200',
    true,
    ARRAY['Révélation de l''Année']
  );

-- Optionnel: actualiser la colonne search_vector si un trigger n'est pas encore en place
-- update public.spectacles set search_vector = public.to_tsvector_french(title || ' ' || coalesce(description,''));
