/*
 * migration: restore grants on public press views + fix dashboard rpc cast
 * ========================================================================
 *
 * purpose:
 *   1. restore `select` for anon/authenticated on the two public press views.
 *   2. fix error 42804 raised by public.communiques_presse_dashboard().
 *
 * root cause (1):
 *   `20260202200333_add_spectacle_paragraphs.sql` was generated by `db diff`
 *   and performs `drop view` + `create or replace view` on both views without
 *   restating any grant. postgres resets the acl on drop, so anon/authenticated
 *   ended up with `Dxtm` only (no `r`), producing
 *   "permission denied for view articles_presse_public" on the public site.
 *
 * root cause (2):
 *   the function declares `evenement_date date` but selects
 *   `evenements.date_debut`, which is `timestamp with time zone`. plpgsql does
 *   not implicitly cast on `return query`, hence
 *   "structure of query does not match function result type".
 *
 * affected objects:
 *   - view public.articles_presse_public (grants only)
 *   - view public.communiques_presse_public (grants only)
 *   - function public.communiques_presse_dashboard() (body only)
 *
 * security:
 *   both views are `security_invoker = true`; rls policies on the underlying
 *   tables keep filtering rows (published articles / public press releases).
 *   granting `select` here restores the intended public read access without
 *   any privilege escalation.
 */

-- ============================================================================
-- 1. public press views: reset then grant explicitly
-- ============================================================================

revoke all on public.articles_presse_public from anon, authenticated;
grant select on public.articles_presse_public to anon, authenticated, service_role;

revoke all on public.communiques_presse_public from anon, authenticated;
grant select on public.communiques_presse_public to anon, authenticated, service_role;

-- ============================================================================
-- 2. admin dashboard function: cast timestamptz to date
-- ============================================================================

create or replace function public.communiques_presse_dashboard()
returns table (
  id bigint,
  title text,
  slug text,
  description text,
  date_publication date,
  public boolean,
  ordre_affichage integer,
  pdf_filename text,
  pdf_size_kb numeric,
  image_url text,
  image_filename text,
  spectacle_titre text,
  evenement_date date,
  createur text,
  created_at timestamptz,
  updated_at timestamptz,
  nb_categories bigint,
  nb_tags bigint
)
language plpgsql
security definer
set search_path = ''
as $$
begin
  -- explicit admin check - throws error if not admin (not just empty array)
  if not (select public.is_admin()) then
    raise exception 'permission denied: admin access required';
  end if;

  return query
  select
    cp.id,
    cp.title,
    cp.slug,
    cp.description,
    cp.date_publication,
    cp.public,
    cp.ordre_affichage,
    pdf_m.filename as pdf_filename,
    round(coalesce(cp.file_size_bytes, pdf_m.size_bytes) / 1024.0, 2) as pdf_size_kb,
    cp.image_url,
    im.filename as image_filename,
    s.title as spectacle_titre,
    -- evenements.date_debut is timestamptz; the declared return type is date
    e.date_debut::date as evenement_date,
    p.display_name as createur,
    cp.created_at,
    cp.updated_at,
    count(cc.category_id) as nb_categories,
    count(ct.tag_id) as nb_tags
  from public.communiques_presse as cp
  left join public.communiques_medias as pdf_cm on cp.id = pdf_cm.communique_id and pdf_cm.ordre = -1
  left join public.medias as pdf_m on pdf_cm.media_id = pdf_m.id
  left join public.communiques_medias as cm on cp.id = cm.communique_id and cm.ordre = 0
  left join public.medias as im on cm.media_id = im.id
  left join public.spectacles as s on cp.spectacle_id = s.id
  left join public.evenements as e on cp.evenement_id = e.id
  left join public.profiles as p on cp.created_by = p.user_id
  left join public.communiques_categories as cc on cp.id = cc.communique_id
  left join public.communiques_tags as ct on cp.id = ct.communique_id
  group by cp.id, pdf_m.filename, pdf_m.size_bytes, im.filename, cp.image_url,
           s.title, e.date_debut, p.display_name
  order by cp.created_at desc;
end;
$$;

comment on function public.communiques_presse_dashboard is
'Admin dashboard function for press releases. SECURITY DEFINER with explicit admin check - throws exception for non-admins instead of returning empty array (proper access control).';

revoke all on function public.communiques_presse_dashboard() from anon, authenticated;
grant execute on function public.communiques_presse_dashboard() to service_role;
