-- Migration: Restore INSERT policies dropped by TASK053 db diff + fix admin view grants
-- Problem: Migration 20260117234007_task053_data_retention.sql generated by
--          `supabase db diff` incorrectly dropped INSERT policies and disabled RLS
-- Affected:
--   - messages_contact: "Validated contact submission" policy dropped
--   - analytics_events: "Validated analytics collection" policy dropped
--   - home_hero_slides: RLS was disabled
--   - communiques_presse_dashboard: SELECT granted to anon/authenticated (should be denied)
-- 
-- Root cause: db diff detected schema differences and generated DROP statements
--             but the policies were not part of declarative schema (managed by migration)

-- ============================================================================
-- 1. RESTORE home_hero_slides RLS
-- ============================================================================

alter table public.home_hero_slides enable row level security;

-- ============================================================================
-- 2. FIX communiques_presse_dashboard grants (SECURITY ISSUE)
-- ============================================================================
-- Problem: View has is_admin() filter but anon/authenticated have SELECT grant
-- This causes empty array return instead of permission denied
-- Solution: Revoke SELECT from anon/authenticated, keep only service_role

revoke all on public.communiques_presse_dashboard from anon;
revoke all on public.communiques_presse_dashboard from authenticated;

-- Grant SELECT only to service_role (for admin backend operations)
grant select on public.communiques_presse_dashboard to service_role;

-- ============================================================================
-- 3. RESTORE messages_contact INSERT policy
-- ============================================================================

-- Recreate the validated contact form policy
create policy "Validated contact submission"
on public.messages_contact for insert
to anon, authenticated
with check (
  -- Required fields non-null
  firstname is not null and firstname <> ''
  and lastname is not null and lastname <> ''
  and email is not null and email <> ''
  and reason is not null
  and message is not null and message <> ''
  and consent = true  -- RGPD mandatory
  
  -- Email format validation
  and email ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'
  
  -- Phone optional but validated if present
  and (phone is null or phone ~* '^\+?[0-9\s\-\(\)]{10,}$')
  
  -- Message length limits (anti-abuse)
  and length(message) between 10 and 5000
);

comment on policy "Validated contact submission" 
  on public.messages_contact is 
'Enforce form validation and RGPD consent. 
Rate limiting (5 req/15min/IP) enforced by application layer (TASK046).';

-- ============================================================================
-- 4. RESTORE analytics_events INSERT policy
-- ============================================================================

-- Recreate the validated analytics collection policy
create policy "Validated analytics collection"
on public.analytics_events for insert
to anon, authenticated
with check (
  -- Required fields non-null
  event_type is not null
  and entity_type is not null
  -- Note: created_at has default now(), no need to check
  
  -- Event type whitelist
  and event_type in ('view', 'click', 'share', 'download')
  
  -- Entity type whitelist
  and entity_type in ('spectacle', 'article', 'communique', 'evenement')
);

comment on policy "Validated analytics collection" 
  on public.analytics_events is 
'Enforce event type whitelisting and temporal validity. 
Rate limiting NOT implemented - monitor for abuse patterns.';

-- ============================================================================
-- 5. VERIFICATION
-- ============================================================================

do $$
declare
  policy_count integer;
  grant_exists boolean;
begin
  -- Verify messages_contact INSERT policy exists
  select count(*) into policy_count
  from pg_policies
  where tablename = 'messages_contact' and cmd = 'INSERT';
  
  if policy_count = 1 then
    raise notice '✅ messages_contact: INSERT policy restored';
  else
    raise exception '❌ messages_contact: Expected 1 INSERT policy, found %', policy_count;
  end if;

  -- Verify analytics_events INSERT policy exists
  select count(*) into policy_count
  from pg_policies
  where tablename = 'analytics_events' and cmd = 'INSERT';
  
  if policy_count = 1 then
    raise notice '✅ analytics_events: INSERT policy restored';
  else
    raise exception '❌ analytics_events: Expected 1 INSERT policy, found %', policy_count;
  end if;

  -- Verify home_hero_slides RLS is enabled
  if exists (
    select 1 from pg_tables 
    where schemaname = 'public' 
    and tablename = 'home_hero_slides' 
    and rowsecurity = true
  ) then
    raise notice '✅ home_hero_slides: RLS re-enabled';
  else
    raise exception '❌ home_hero_slides: RLS still disabled';
  end if;

  -- Verify communiques_presse_dashboard grants revoked from anon/authenticated
  select exists (
    select 1 from information_schema.table_privileges
    where table_name = 'communiques_presse_dashboard'
    and privilege_type = 'SELECT'
    and grantee in ('anon', 'authenticated')
  ) into grant_exists;
  
  if grant_exists then
    raise exception '❌ communiques_presse_dashboard: SELECT still granted to anon/authenticated';
  else
    raise notice '✅ communiques_presse_dashboard: SELECT revoked from anon/authenticated';
  end if;

  raise notice '✅ All security policies restored successfully';
end;
$$;
